### ISSUE TITLE
Formating of input data

### ISSUE THREAD

**Issue by pakiessling** [sunericd/SPRITE#1]
Hi,

I really like the idea behind SPRITE and TISSUE and want to try it with my own data.

A part I am unsure about is the the formating of the input data.

For example in the [tests/data](https://github.com/sunericd/SPRITE/tree/master/tests/data) you seem to use count data for the spatial and normalized + log1p for the scRNA reference.

In the SPAGE tutorial the authors use 
```
def Log_Norm_cpm(x):
    return np.log(((x/np.sum(x))*1000000) + 1) and
  
def Log_Norm_spatial(x):
    return np.log(((x/np.sum(x))*np.median(cell_count)) + 1)
```

How much does this matter in your expirience and what would be your recommendation?

Thank you!

**Comment by sunericd** [comment]
In my experience, whether to normalize the spatial data doesn't seem to matter too much when it comes to performance. Either should work for TISSUE or SPRITE. 

In the TISSUE and SPRITE manuscripts, we based our normalization choice on empirical results showing generally better performance from an earlier [benchmarking effort](https://www.nature.com/articles/s41592-022-01480-9/figures/8), which might also be helpful to you.

**Comment by pakiessling** [comment]
I was unfamiliar with that supplement ty!
